### ISSUE TITLE
Don't panic when config not found

### ISSUE THREAD

**Issue by arush-sal** [kubernauts/tk8#19]
Issue: When no config file is found the CLI exit with a panic, instead it should exit by logging a `Fatal` message

```
[ec2-user@ip-10-0-0-137 bin]$ ./tk8 cluster aws -c
Found terraform at /usr/bin/terraform
Terraform v0.11.7

panic: fatal error config file: Config File "config" Not Found in "[/home/ec2-user /home/ec2-user/go/bin /tk8]"

goroutine 1 [running]:
github.com/kubernauts/tk8/vendor/github.com/kubernauts/tk8/cmd.glob..func2(0xae3560, 0xc420043040, 0x0, 0x1)
	/home/ec2-user/go/src/github.com/kubernauts/tk8/vendor/github.com/kubernauts/tk8/cmd/aws.go:248 +0x3fb5
github.com/kubernauts/tk8/vendor/github.com/spf13/cobra.(*Command).execute(0xae3560, 0xc420043030, 0x1, 0x1, 0xae3560, 0xc420043030)
	/home/ec2-user/go/src/github.com/kubernauts/tk8/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/kubernauts/tk8/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xae3ee0, 0xae4140, 0xc4200e0700, 0xae4030)
	/home/ec2-user/go/src/github.com/kubernauts/tk8/vendor/github.com/spf13/cobra/command.go:852 +0x334
github.com/kubernauts/tk8/vendor/github.com/spf13/cobra.(*Command).Execute(0xae3ee0, 0x0, 0xc420117f48)
	/home/ec2-user/go/src/github.com/kubernauts/tk8/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/kubernauts/tk8/vendor/github.com/kubernauts/tk8/cmd.Execute()
	/home/ec2-user/go/src/github.com/kubernauts/tk8/vendor/github.com/kubernauts/tk8/cmd/root.go:43 +0x31
main.main()
	/home/ec2-user/go/src/github.com/kubernauts/tk8/main.go:20 +0x20
```

**Comment by arush-sal** [comment]
Fixed in fa19ac947045aea905c94c3567bd401259a0fcbe
